@url = http://localhost:8080/api

# It should response with OK status.
POST {{url}}/v1/users HTTP/1.1
Content-Type: application/json

{
    "name": "Juan Rodriguez",
    "email": "juan2@rodrigudez.org",
    "password": "h32",
    "phones": [
        {
            "number": "1234567",
            "citycode": "1",
            "contrycode": "57"
        }
    ]
}
###

# It should response with "Formato de correo incorrecto".
POST {{url}}/v1/users HTTP/1.1
Content-Type: application/json

{
    "name": "Juan Rodriguez",
    "email": "juan2rodrigudez.org",
    "password": "h32",
    "phones": []
}
###
# It should response with "Formato de contraseña incorrecto".
POST {{url}}/v1/users HTTP/1.1
Content-Type: application/json

{
    "name": "Juan Rodriguez",
    "email": "juan2@rodrigudez.org",
    "password": "h",
    "phones": []
}
###
# It should response with "Correo ya registrado".
POST {{url}}/v1/users HTTP/1.1
Content-Type: application/json

{
    "name": "Juan Rodriguez",
    "email": "juan2@rodrigudez.org",
    "password": "h32",
    "phones": []
}
###
# It should response with "Nombre de usuario obligatorio".
POST {{url}}/v1/users HTTP/1.1
Content-Type: application/json

{
    "name": "",
    "email": "juan@rodrigudez.org",
    "password": "h32",
    "phones": []
}